cmake:
  - 3.18.*                     # [x86_64]
  - 3.19.*                     # [ppc64le]
c_compiler_version:
  - 8.*                        # [cudatoolkit == '11.2']
cxx_compiler_version:
  - 8.*                        # [cudatoolkit == '11.2']

